---
- name: "Check whether the node exporter has already been installed"
  stat:
    path: "/usr/local/bin/mysqld_exporter"
    checksum_algorithm: "{{ mysqld_exporter_checksum_algorithm }}"
  register: "bin"

- name: "Fetch the archive from GitHub"
  get_url:
    url: "https://github.com/prometheus/mysqld_exporter/releases/download/v{{ mysqld_exporter_version }}/mysqld_exporter-{{ mysqld_exporter_version }}.linux-{{ mysqld_exporter_arch }}.tar.gz"
    dest: "/tmp/mysqld_exporter-{{ mysqld_exporter_version }}.linux-{{ mysqld_exporter_arch }}.tar.gz"
    checksum: "{{ mysqld_exporter_checksum_algorithm }}:{{ mysqld_exporter_checksum_archive }}"
  when: bin.stat.exists == False or
        bin.stat.checksum != mysqld_exporter_checksum_binary

- name: "Unpack the archive in /tmp"
  unarchive:
    remote_src: true
    src: "/tmp/mysqld_exporter-{{ mysqld_exporter_version }}.linux-{{ mysqld_exporter_arch }}.tar.gz"
    dest: "/tmp"
  when: bin.stat.exists == False or
        bin.stat.checksum != mysqld_exporter_checksum_binary

- name: "Move node-exporter to the /usr/local/bin/node-exporter"
  copy:
    remote_src: true
    src: "/tmp/mysqld_exporter-{{ mysqld_exporter_version }}.linux-{{ mysqld_exporter_arch }}/mysqld_exporter"
    dest: "/usr/local/bin/mysqld_exporter"
    owner: "root"
    group: "root"
    mode: "u=rwx,g=rwx,o=rwx"
  when: bin.stat.exists == False or
        bin.stat.checksum != mysqld_exporter_checksum_binary
  notify: "restart mysqld_exporter"

- name: "Clean the /tmp/ dir up"
  file:
    path: "{{ item }}"
    state: "absent"
  with_items:
    - "/tmp/mysqld_exporter-{{ mysqld_exporter_version }}.linux-{{ mysqld_exporter_arch }}.tar.gz"
    - "/tmp/mysqld_exporter-0.14.0.linux-{{ mysqld_exporter_arch }}/"
  when: bin.stat.exists == False or
        bin.stat.checksum != mysqld_exporter_checksum_binary
